# Generated by Django 3.1.1 on 2021-01-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Language', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic_name', models.CharField(max_length=200)),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheats_app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheats_app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard_menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='uploads/languages_logo')),
                ('back_color', models.CharField(choices=[('card-header-warning', 'Warning'), ('card-header-success', 'Success'), ('card-header-info', 'Info'), ('card-header-secondary', 'Secondary'), ('card-header-white', 'White')], max_length=49)),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheats_app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='compiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compiler', models.CharField(max_length=200)),
                ('editor_name', models.CharField(max_length=200)),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheats_app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Code_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic_name', models.CharField(max_length=200)),
                ('code', models.TextField()),
                ('Language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheats_app.language')),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheats_app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='cheats_app_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheats_app.topic')),
            ],
        ),
    ]
