# Generated by Django 3.1.1 on 2021-01-31 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheats_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compiler',
            name='documentation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='cheats_app.documentation'),
        ),
        migrations.DeleteModel(
            name='cheats_app_book',
        ),
    ]
