# Generated by Django 3.1.1 on 2021-01-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheats_app', '0002_auto_20210131_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='books_module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_images', models.ImageField(upload_to='uploads/books_logo')),
                ('topic_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheats_app.topic')),
            ],
        ),
    ]
